title: Low Level Roadmap
author: NeZvers
email: spam@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Collection of examples and explanations for things to know to be a good programmer.

# social links
twitter_username: nezversstudio # DO NOT include the @ character, or else the build will fail!
github_username:  nezvers # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

markdown: GFM # markdown: kramdown or markdown: GFM (GitHub Flavored Markdown) 
